---
title: "data_cleaning"
output: html_document
date: "2023-01-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(purrr)
library(dplyr)

```

```{r}
folder_path <- '~/PerformanceMarketing/Form Submission/2024/January_2024/January_all' 
filenames <- list.files(folder_path, pattern = "\\.csv$", full.names = TRUE)

combo_data <- purrr::map_df(filenames, 
              ~read_csv(.x) |> mutate(filename = .x))
```


```{r}


common_path <- dirname(filenames[1])

combo_data2 <- combo_data |>
  mutate(filename = as.character(filename)) |>
  mutate(filename = str_replace(filename, common_path, ""),
         filename = str_remove(filename, "/")) |> 
  mutate(filename = str_replace_all(filename, "\\([0-9a-f]+\\)-\\d{4}-\\d{2}-\\d{2}\\.csv", "")) |>
  rename(phone_number = `手机号码`) |>
  mutate(phone_number = str_replace_all(phone_number, "-", "") |> 
                          str_replace_all("[^0-9]", "")) |> 
  mutate(
    channel = case_when(
      str_detect(filename, "(?i)SEM|Blog Pages Contact us") | str_detect(utm_source,"(?i)google") ~ "SEM",
      str_detect(filename, "(?i)SEO|Contact us") ~ "SEO",
      str_detect(filename, "(?i)sMS") ~ "SMS",
      str_detect(filename, "(?i)Brizo|(?i)DM") | str_detect(utm_medium,"(?i)DirectMail")~ "DM")) |> 
  select(channel, everything(),-c("...1","...10","...12", "...11", `User Agent`,`User ID`, `Terms and Conditions`,`餐馆名字`,`名字`)) |> 
  rename(Create_Date = `Created At`) |> 
  mutate(
    Create_Date = as_date(Create_Date), # Convert Create_Date to Date if not already in Date format
    week = case_when(
      Create_Date >= as_date("2024-01-01") & Create_Date <= as_date("2024-01-07") ~ "1/1-1/7",
      Create_Date >= as_date("2024-01-08") & Create_Date <= as_date("2024-01-14") ~ "1/8-1/14",
      Create_Date >= as_date("2024-01-15") & Create_Date <= as_date("2024-01-21") ~ "1/15-1/21",
      Create_Date >= as_date("2024-01-22") & Create_Date <= as_date("2024-01-31") ~ "1/22-1/31",
      TRUE ~ NA_character_ # Default case if no conditions are met
    )
  ) |> 
  select(week,channel, everything())
```


```{r}
combo_data2 |> 
  group_by(channel) |> 
  summarize(form_fill_numbers=n()) |> 
  arrange(desc(form_fill_numbers)) -> summary_table

write_csv(summary_table, "form_fill_counts_by_channel.csv")
write_csv(combo_data2,"all_form_fill.csv", na = "")
```