---
title: "data_cleaning"
output: html_document
date: "2023-01-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(purrr)
library(dplyr)

```

```{r}
folder_path <- '~/Performance Analysis/Form Submission/elementor' 
filenames <- list.files(folder_path, pattern = "\\.csv$", full.names = TRUE)

combo_data <- purrr::map_df(filenames, 
              ~read_csv(.x) |> mutate(filename = .x))
```


```{r}


common_path <- dirname(filenames[1])

combo_data <- combo_data |>
  mutate(filename = as.character(filename)) |>
  mutate(filename = str_replace(filename, common_path, ""),
         filename = str_remove(filename, "/")) |> 
  mutate(filename = str_replace_all(filename, "\\([0-9a-f]+\\)-\\d{4}-\\d{2}-\\d{2}\\.csv", "")) |>
  rename(phone_number = `手机号码`) |>
  mutate(phone_number = str_replace_all(phone_number, "-", "") |> 
                          str_replace_all("[^0-9]", "")) |> 
  mutate(
    channel = case_when(
      str_detect(filename, "(?i)SEM|Blog Pages Contact us") ~ "SEM",
      str_detect(filename, "(?i)SEO|Contact us") ~ "SEO",
      str_detect(filename, "(?i)sMS") ~ "SMS",
      str_detect(filename, "(?i)Brizo|(?i)DM") ~ "DM")) |> 
  select(channel, everything(),-"...1",-"...10",-"...12")
```


```{r}
combo_data |> 
  group_by(channel) |> 
  summarize(form_fill_numbers=n()) |> 
  arrange(desc(form_fill_numbers)) -> summary_table

write_csv(summary_table, "form_fill_counts_by_channel.csv")
write_csv(combo_data,"all_form_fill.csv", na = "")
```