<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yuka Chen">

<title>DM Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="DM_Analysis2_files/libs/clipboard/clipboard.min.js"></script>
<script src="DM_Analysis2_files/libs/quarto-html/quarto.js"></script>
<script src="DM_Analysis2_files/libs/quarto-html/popper.min.js"></script>
<script src="DM_Analysis2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="DM_Analysis2_files/libs/quarto-html/anchor.min.js"></script>
<link href="DM_Analysis2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="DM_Analysis2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="DM_Analysis2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="DM_Analysis2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="DM_Analysis2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="DM_Analysis2_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="DM_Analysis2_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">DM Analysis</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Yuka Chen </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Marketing Operation Inter @ Wonders<br>
            </p><center>
          <p></p>
      </center></div>
    </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  

</header>

<section id="direct-mail-analysis" class="level1">
<h1>Direct Mail Analysis</h1>
<section id="objective" class="level2">
<h2 class="anchored" data-anchor-id="objective">1. Objective</h2>
<p>The objective of this project is to understand the target audience’s reasons for not filling out the information after scanning the QR code. Since the data set is limited in size for each campaign, I have combined all data from all campaign who have scanned the QR code and group based on they fill the information form or not.</p>
</section>
<section id="limitation" class="level2">
<h2 class="anchored" data-anchor-id="limitation">2. Limitation</h2>
<p>As the data sources for June and July used three different formats, it was quite challenging to clean and combine the data. Moreover, it seems that most utm_id values do not match with our Snowball_ID.</p>
</section>
<section id="highlights-of-the-report" class="level2">
<h2 class="anchored" data-anchor-id="highlights-of-the-report">3. Highlights of the report</h2>
<ul>
<li>People in California, Colorado, Illinois, Indiana, and Wisconsin are more likely to fill in information than people living in other states.</li>
<li>Individuals who own or manage Asian Fusion and Chinese restaurants are more likely to fill in the information than those associated with other types of restaurants.</li>
<li>The role of the target audience does not have any significant relationship with filling in the information.</li>
</ul>
</section>
<section id="take" class="level2">
<h2 class="anchored" data-anchor-id="take">4. Take</h2>
<p>People in certain demography do have some kind of relationship to do with their decision on filling the information after they scanned our QR code.</p>
</section>
<section id="whats-next" class="level2">
<h2 class="anchored" data-anchor-id="whats-next">5. What’s Next?</h2>
<ul>
<li><strong>Find out the data transformation discrepancy (why not match) so we can predict clients behavior better</strong></li>
<li>Run other machine learning model to see if we can get better predictions</li>
<li>Run the prediction models by campaigns (i.e.&nbsp;June/July audience info contains Gender, Owner Ethnicity)</li>
<li>Clean/Maintain the data well so we can run a model better - better prediction. We could calculate the possibility of a person to fill the information by their personal background and restaurants information.</li>
<li>find out pattern on people who didn’t scan vs scanned (break the first barrier)</li>
</ul>
</section>
</section>
<section id="analysis" class="level1">
<h1>Analysis</h1>
<section id="data-summary-table-and-visualization" class="level2">
<h2 class="anchored" data-anchor-id="data-summary-table-and-visualization">6. Data Summary Table and Visualization</h2>
<section id="state" class="level3">
<h3 class="anchored" data-anchor-id="state">State</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">State</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Didn't Fill</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Filled</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">CA</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">111</td>
</tr>
<tr class="even">
<td style="text-align: left;">FL</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">46</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TX</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="even">
<td style="text-align: left;">PA</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OH</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">26</td>
</tr>
<tr class="even">
<td style="text-align: left;">NY</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VA</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">21</td>
</tr>
<tr class="even">
<td style="text-align: left;">MA</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LA</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">14</td>
</tr>
<tr class="even">
<td style="text-align: left;">OR</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MD</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">NJ</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GA</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">14</td>
</tr>
<tr class="even">
<td style="text-align: left;">MI</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TN</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">NC</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UT</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">WA</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IL</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">MO</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AL</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">IN</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SC</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">CO</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MN</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">NV</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OK</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">AR</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AZ</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">DC</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DE</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">KS</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MT</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">NE</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">WV</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">CT</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IA</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">KY</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MS</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">ND</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NM</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unknown</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VT</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">WI</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">WY</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">ME</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">417</td>
<td style="text-align: right;">128</td>
<td style="text-align: right;">489</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="DM_Analysis2_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="categorty" class="level3">
<h3 class="anchored" data-anchor-id="categorty">Categorty</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">New_Category</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Didn't Fill</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Filled</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Chinese</td>
<td style="text-align: right;">189</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">289</td>
</tr>
<tr class="even">
<td style="text-align: left;">Japanese</td>
<td style="text-align: right;">190</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">226</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Asian Fusion</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">89</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unknown</td>
<td style="text-align: right;">136</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">144</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cajun Seafood</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">22</td>
</tr>
<tr class="even">
<td style="text-align: left;">Szechuan</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sichuan</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Taiwanese</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">618</td>
<td style="text-align: right;">155</td>
<td style="text-align: right;">770</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="DM_Analysis2_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>By plot, we can see that Cajun Seafood and Japanese restaurants scanned the QR code, but didn’t fill in the information.</p>
</section>
<section id="contact_title" class="level3">
<h3 class="anchored" data-anchor-id="contact_title">Contact_Title</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Contact_Title</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Didn't Fill</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Filled</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Unknown</td>
<td style="text-align: right;">390</td>
<td style="text-align: right;">94</td>
<td style="text-align: right;">484</td>
</tr>
<tr class="even">
<td style="text-align: left;">Owner</td>
<td style="text-align: right;">83</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">127</td>
</tr>
<tr class="odd">
<td style="text-align: left;">General</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">31</td>
</tr>
<tr class="even">
<td style="text-align: left;">OWNER</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MANAGER</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">21</td>
</tr>
<tr class="even">
<td style="text-align: left;">ADMINISTRATION</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Back of the House</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">CHIEF_EXECUTIVE_OFFICER</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FINANCE EXEC</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Finance</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Front of the House</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">GENERAL_MANAGER</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MANAGING_MEMBER</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">MANAGING_PARTNER</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MEMBER</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PARTNER</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PRESIDENT</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">PRINCIPAL</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SECRETARY</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sales &amp; Marketing</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VICE PRESIDENT</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">618</td>
<td style="text-align: right;">155</td>
<td style="text-align: right;">738</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="DM_Analysis2_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="information-source" class="level3">
<h3 class="anchored" data-anchor-id="information-source">Information Source</h3>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">InfoSource</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Didn't Fill</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Filled</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Brizo</td>
<td style="text-align: right;">255</td>
<td style="text-align: right;">126</td>
<td style="text-align: right;">381</td>
</tr>
<tr class="even">
<td style="text-align: left;">greendot</td>
<td style="text-align: right;">164</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">178</td>
</tr>
<tr class="odd">
<td style="text-align: left;">google</td>
<td style="text-align: right;">129</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">137</td>
</tr>
<tr class="even">
<td style="text-align: left;">canada</td>
<td style="text-align: right;">69</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">76</td>
</tr>
<tr class="odd">
<td style="text-align: left;">existing_clients</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">618</td>
<td style="text-align: right;">155</td>
<td style="text-align: right;">772</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="DM_Analysis2_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="models" class="level2">
<h2 class="anchored" data-anchor-id="models">7. Models</h2>
<p>I ran logistic regression to predict which group are more likely to fill up the information. Unfortunately I had issues when I run a model with all variables and wasn’t able to debug it. So instead I ran model separately. The downside of doing it is that we can not consider the possibilities of when all information happened overrall.</p>
<section id="predicting-by-state" class="level3">
<h3 class="anchored" data-anchor-id="predicting-by-state">7.1 predicting by State</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = fill_info_num ~ State, family = binomial(logit), 
    data = test)

Coefficients:
               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)    -2.07944    0.53033  -3.921 8.82e-05 ***
StateAL         0.98083    0.97361   1.007   0.3137    
StateAR         0.69315    1.23744   0.560   0.5754    
StateAZ       -15.48663 1978.09024  -0.008   0.9938    
StateBC         0.05129    0.71244   0.072   0.9426    
StateCA         1.21924    0.56954   2.141   0.0323 *  
StateCO         1.85630    0.85513   2.171   0.0299 *  
StateCT       -15.48663 3956.18036  -0.004   0.9969    
StateDC         1.38629    1.01550   1.365   0.1722    
StateDE       -15.48663 2284.10184  -0.007   0.9946    
StateFL         0.79851    0.63955   1.249   0.2118    
StateGA         1.16315    0.79451   1.464   0.1432    
StateIA       -15.48663 3956.18036  -0.004   0.9969    
StateIL         1.74297    0.79000   2.206   0.0274 *  
StateIN         1.89712    0.80493   2.357   0.0184 *  
StateKS       -15.48663 2284.10184  -0.007   0.9946    
StateKY       -15.48663 3956.18036  -0.004   0.9969    
StateLA         0.28768    0.92983   0.309   0.7570    
StateMA       -15.48663 1057.33380  -0.015   0.9883    
StateMB        -0.11778    1.17998  -0.100   0.9205    
StateMD        -0.31845    1.17139  -0.272   0.7857    
StateME        19.64551 3956.18036   0.005   0.9960    
StateMI         0.87547    0.84533   1.036   0.3004    
StateMN         1.16315    0.99058   1.174   0.2403    
StateMO         0.82668    0.96130   0.860   0.3898    
StateMS         3.17805    1.27066   2.501   0.0124 *  
StateMT       -15.48663 2284.10184  -0.007   0.9946    
StateNB         0.98083    1.27066   0.772   0.4402    
StateNC         1.38629    0.81009   1.711   0.0870 .  
StateND       -15.48663 3956.18036  -0.004   0.9969    
StateNE       -15.48663 2284.10184  -0.007   0.9946    
StateNJ        -0.31845    1.17139  -0.272   0.7857    
StateNL       -15.48663 1978.09024  -0.008   0.9938    
StateNM       -15.48663 3956.18036  -0.004   0.9969    
StateNS       -15.48663 1495.29571  -0.010   0.9917    
StateNV         1.16315    0.99058   1.174   0.2403    
StateNY        -0.17185    0.91317  -0.188   0.8507    
StateOH         0.87547    0.70563   1.241   0.2147    
StateOK       -15.48663 1769.25771  -0.009   0.9930    
StateON         0.10789    0.62034   0.174   0.8619    
StateOR       -15.48663 1142.05101  -0.014   0.9892    
StatePA         1.06784    0.67209   1.589   0.1121    
StateQC        -1.01160    1.15183  -0.878   0.3798    
StateSC         0.98083    0.97361   1.007   0.3137    
StateSK         1.51983    0.82104   1.851   0.0642 .  
StateTN         1.26851    0.80147   1.583   0.1135    
StateTX         0.47000    0.72198   0.651   0.5150    
StateUnknown  -15.48663 3956.18036  -0.004   0.9969    
StateUT         0.69315    0.95197   0.728   0.4665    
StateVA         0.91629    0.73739   1.243   0.2140    
StateVT       -15.48663 3956.18036  -0.004   0.9969    
StateWA         1.38629    0.81009   1.711   0.0870 .  
StateWI         2.77259    1.33463   2.077   0.0378 *  
StateWV         1.38629    1.33463   1.039   0.2989    
StateWY       -15.48663 3956.18036  -0.004   0.9969    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 774.73  on 772  degrees of freedom
Residual deviance: 691.51  on 718  degrees of freedom
AIC: 801.51

Number of Fisher Scoring iterations: 16</code></pre>
</div>
</div>
<section id="interpretation" class="level5">
<h5 class="anchored" data-anchor-id="interpretation">Interpretation</h5>
<ul>
<li><p>**CA, CO, IL, IN, WI has a positive coefficient with a small p-value ( &lt;0.05, *), which suggests that people in these states have higher log-odds of the response variable compared to the reference state.**</p></li>
<li><p>The coefficients for each state (e.g., AL, AR, AZ, etc.) indicate how much the likelihood of people filling in information in that specific state differs from the baseline state.</p></li>
<li><p>For example, in the case of CA, it has a positive coefficient of approximately 1.21924, and a p-value of 0.0323 (*), suggesting that people in California are more likely to fill in information after scanning the QR code compared to the baseline state.</p></li>
<li><p>Conversely, for IL, it has a positive coefficient of approximately 1.74297, and a p-value of 0.0274 (*), indicating that people in Illinois are also more likely to fill in information compared to the baseline state.</p></li>
<li><p>MS has a positive coefficient of approximately 3.17805, and a p-value of 0.0124 (*), implying that people in Mississippi have a significantly higher likelihood of filling in information compared to the baseline state.</p></li>
<li><p>CO, IN, NC, and WI also have positive coefficients with p-values less than 0.05 (*), suggesting that people in these states are more likely to fill in information compared to the baseline.</p></li>
<li><p>On the other hand, some states like AZ, CT, DE, IA, KS, KY, NM, ND, ON, OR, TX, UT, VT, and WY have coefficients with p-values greater than 0.05, indicating that there is no statistically significant difference in the likelihood of people filling in information in these states compared to the baseline state.</p></li>
<li><p>Overall, this analysis examines how the state variable relates to the likelihood of people filling in information after scanning a QR code, with positive coefficients suggesting a higher likelihood, and negative coefficients suggesting a lower likelihood, compared to the baseline state (which is not explicitly mentioned in the output).</p></li>
</ul>
</section>
</section>
<section id="predicting-by-established-years" class="level3">
<h3 class="anchored" data-anchor-id="predicting-by-established-years">7.2 predicting by Established Years</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = fill_info_num ~ Year_Established, family = binomial(logit), 
    data = test)

Coefficients:
                 Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)      11.15029   23.27560   0.479    0.632
Year_Established -0.00585    0.01162  -0.504    0.615

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 221.04  on 168  degrees of freedom
Residual deviance: 220.79  on 167  degrees of freedom
  (604 observations deleted due to missingness)
AIC: 224.79

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<section id="interpretation-1" class="level5">
<h5 class="anchored" data-anchor-id="interpretation-1">Interpretation</h5>
<ul>
<li>The result shows the restaurant established years are not statistically significant for our data (target audiences). It could due to lack of data points.</li>
</ul>
</section>
</section>
<section id="predicting-by-employee_size" class="level3">
<h3 class="anchored" data-anchor-id="predicting-by-employee_size">7.3 predicting by Employee_Size (*)</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = fill_info_num ~ Employee_Size, family = binomial(logit), 
    data = test)

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   -2.02743    0.43662  -4.643 3.43e-06 ***
Employee_Size -0.04973    0.04939  -1.007    0.314    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 132.16  on 235  degrees of freedom
Residual deviance: 130.59  on 234  degrees of freedom
  (537 observations deleted due to missingness)
AIC: 134.59

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<section id="interpretation-2" class="level5">
<h5 class="anchored" data-anchor-id="interpretation-2">Interpretation</h5>
<ul>
<li><p>The coefficient for Employee_Size is approximately -0.01194, and it has a relatively high p-value (0.74), indicating that there is no statistically significant relationship between the number of employees in a restaurant and the likelihood of people filling in information after scanning the QR code. The p-value is greater than the conventional significance level (0.05), suggesting that the variable “Employee_Size” does not have a significant impact on the outcome.</p></li>
<li><p>Overall, based on this analysis, the number of employees in a restaurant does not appear to be a significant predictor of whether people will fill in information after scanning the QR code, at least when considering data excluding cases.</p></li>
</ul>
</section>
</section>
<section id="predicting-by-restaurant-types" class="level3">
<h3 class="anchored" data-anchor-id="predicting-by-restaurant-types">7.4 predicting by restaurant types</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = fill_info_num ~ New_Category, family = binomial(logit), 
    data = test[test$New_Category != "Unknown", ])

Coefficients:
                          Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                -2.1848     0.3516  -6.214 5.16e-10 ***
New_CategoryCajun Seafood  -0.8597     1.0822  -0.794    0.427    
New_CategoryChinese         1.5482     0.3727   4.154 3.27e-05 ***
New_CategoryJapanese        0.5213     0.3958   1.317    0.188    
New_CategorySichuan       -12.3813   882.7434  -0.014    0.989    
New_CategorySzechuan       16.7509   882.7434   0.019    0.985    
New_CategoryTaiwanese     -12.3813   882.7434  -0.014    0.989    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 683.99  on 628  degrees of freedom
Residual deviance: 637.42  on 622  degrees of freedom
AIC: 651.42

Number of Fisher Scoring iterations: 13</code></pre>
</div>
</div>
<section id="interpretation-3" class="level5">
<h5 class="anchored" data-anchor-id="interpretation-3">Interpretation</h5>
<ul>
<li><p>In this logistic regression analysis, the “Intercept” represents the baseline likelihood of people filling in information after scanning a QR code when the New_Category is Asian Fusion.</p></li>
<li><p>The coefficient for Asian Fusion is -2.1848, and it has a low p-value (***), indicating that when the restaurant’s category is Asian Fusion, there is a statistically significant decrease in the likelihood of people filling in information compared to other types of restaurants.</p></li>
<li><p>The coefficient for Chinese is 1.5482, and it has a low p-value (***), indicating that when the restaurant’s category is Chinese, there is a statistically significant increase in the likelihood of people filling in information compared to the baseline “Asian Fusion” category.</p></li>
<li><p>Other New_Category coefficients, such as “Cajun Seafood,Japanese, Sichuan, Szechuan, Taiwanese, and Unknown, do not show a statistically significant influence on the likelihood of people filling in information, as their p-values are higher than the conventional significance level (0.05).</p></li>
<li><p>Overall, the type of restaurant category, specifically “Chinese,” appears to be associated with a statistically significant increase in the likelihood of people filling in information after scanning the QR code, compared to the baseline category, “Asian Fusion.”</p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = fill_info_num ~ Contact_Title, family = binomial(logit), 
    data = test[test$Contact_Title != "Unknown", ])

Coefficients:
                                       Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)                          -1.857e+01  4.612e+03  -0.004    0.997
Contact_TitleBack of the House       -2.157e-07  6.523e+03   0.000    1.000
Contact_TitleCHIEF_EXECUTIVE_OFFICER -2.160e-07  7.989e+03   0.000    1.000
Contact_TitleFinance                 -2.157e-07  7.989e+03   0.000    1.000
Contact_TitleFINANCE EXEC            -2.158e-07  7.989e+03   0.000    1.000
Contact_TitleFront of the House      -2.156e-07  6.523e+03   0.000    1.000
Contact_TitleGeneral                  1.824e+01  4.612e+03   0.004    0.997
Contact_TitleGENERAL_MANAGER         -2.156e-07  7.989e+03   0.000    1.000
Contact_TitleMANAGER                  1.557e+01  4.612e+03   0.003    0.997
Contact_TitleMANAGING_MEMBER         -2.157e-07  7.989e+03   0.000    1.000
Contact_TitleMANAGING_PARTNER        -2.157e-07  7.989e+03   0.000    1.000
Contact_TitleMEMBER                  -2.157e-07  7.989e+03   0.000    1.000
Contact_TitleOwner                    1.793e+01  4.612e+03   0.004    0.997
Contact_TitleOWNER                    1.539e+01  4.612e+03   0.003    0.997
Contact_TitlePARTNER                 -2.157e-07  7.989e+03   0.000    1.000
Contact_TitlePRESIDENT               -2.157e-07  5.157e+03   0.000    1.000
Contact_TitlePRINCIPAL               -2.157e-07  5.099e+03   0.000    1.000
Contact_TitleSales &amp; Marketing       -2.157e-07  7.989e+03   0.000    1.000
Contact_TitleSECRETARY               -2.157e-07  7.989e+03   0.000    1.000
Contact_TitleVICE PRESIDENT          -2.157e-07  6.523e+03   0.000    1.000

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 297.89  on 288  degrees of freedom
Residual deviance: 239.28  on 269  degrees of freedom
AIC: 279.28

Number of Fisher Scoring iterations: 17</code></pre>
</div>
</div>
<ul>
<li><p>The <em>Intercept</em> represents the baseline likelihood of filling in information when all other factors are zero. It’s not statistically significant, indicating that the baseline likelihood is not significantly different from zero.</p></li>
<li><p>The coefficients for different Contact_Title categories show how each category influences the likelihood of filling in information compared to a reference category (which is not explicitly mentioned). However, the p-values for most coefficients are very high, indicating that these categories don’t significantly impact the likelihood of filling in information.</p></li>
<li><p><strong>Overall, the Contact_Title variable, as included in the model, doesn’t appear to have a statistically significant influence on whether people fill in information after scanning the QR code.</strong></p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = fill_info_num ~ Campaign, family = binomial(logit), 
    data = test)

Coefficients:
                       Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)             -2.4587     0.1935 -12.708   &lt;2e-16 ***
CampaignFree Trail      -0.5617     0.7495  -0.749    0.454    
CampaignMooncake         2.1813     0.2277   9.580   &lt;2e-16 ***
CampaignNew Restaurant -14.1074   489.8051  -0.029    0.977    
CampaignSummer          -0.8184     0.7459  -1.097    0.273    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 774.73  on 772  degrees of freedom
Residual deviance: 623.31  on 768  degrees of freedom
AIC: 633.31

Number of Fisher Scoring iterations: 15</code></pre>
</div>
</div>
</section>
<section id="interpretation-4" class="level5">
<h5 class="anchored" data-anchor-id="interpretation-4">Interpretation</h5>
<ul>
<li><p>The model used Iphone campaign as a base line, meaning the intercept, and the estimated coefficient is -2.4587. It is statistically significant (p-value &lt; 0.001), suggesting that this campaign has a significant negative impact on the log-odds of fill_info_num. As the coefficient is negative, being part of the Iphone campaign is associated with lower odds of fill_info_num being 1.</p></li>
<li><p>For the Free Trail campaign, the estimated coefficient is -0.5617. However, it is not statistically significant (p-value = 0.454), indicating that this campaign does not have a significant impact on the log-odds of fill_info_num.</p></li>
<li><p><strong>For the Mooncake campaign, the estimated coefficient is 2.1813. It is statistically significant (p-value &lt; 0.001), suggesting that this campaign has a significant positive impact on the log-odds of fill_info_num. As the coefficient is positive, being part of the Mooncake campaign is associated with higher odds of fill_info_num being 1.</strong></p></li>
<li><p>For the New Restaurant campaign, the estimated coefficient is -14.1074. However, it is not statistically significant (p-value = 0.977), indicating that this campaign does not have a significant impact on the log-odds of fill_info_num.</p></li>
<li><p>For the Summer campaign, the estimated coefficient is -0.8184. However, it is not statistically significant (p-value = 0.273), indicating that this campaign does not have a significant impact on the log-odds of fill_info_num.</p></li>
</ul>
<p>Overall, the Mooncake campaign appears to have a significant positive impact on the likelihood of people filling the information form (= fill_info_num being 1), while the other campaigns do not seem to have a significant effect based on their p-values</p>
</section>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>